### PR TITLE
feat: fragment viewgroup support in android

### PR DESCRIPTION
**Pull request by harshgarg18**
[ignore example app changes]

### CODE REVIEW

**Review by JamesGeorg — APPROVED** [review]
It is possible in a vanilla hyper sdk integration for a single process to have multiple rootViews. 
But that looks difficult in plugin; Maybe we should consider such cases later.

**Review by vraghunandhan — APPROVED** [review]

**Review by Subhash703 — APPROVED** [review]

**Comment by harshgarg18** [comment]
@Subhash703 - remove demo app changes

**Comment by harshgarg18** [comment]
@Subhash703 - can we rename HyperView to HyperFragmentView / HyperFragmentViewGroup to distinguish it with the container view changes we did in flutter?

**Comment by harshgarg18** [comment]
iOS changes missing?

**Review by vraghunandhan — APPROVED** [review]

**Pull request merged**
